version: '3.3'

services:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_vol:/r_data

  redis_insight:
    image: redislabs/redisinsight:latest
    restart: always
    depends_on:
      - redis
    ports:
      - 8001:8001
    volumes:
      - redis_insight_vol:/ri_data

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  web:
    build: .
    restart: always
    working_dir: /app
    ports:
      - 8080:8000
    # volumes:
    #   - ./:/app:Z
    depends_on:
      - redis
      - db
    environment: 
      REDIS_URL: redis://redis:6379/0

      USE_POSTGRES: 'True'
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: postgres

      DEBUG: 'False'
      DISABLE_SSL: 'False'

      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
    command: bash -c "python manage.py migrate && gunicorn telegram_sendall.wsgi --bind 0.0.0.0:8000"

  worker:
    build: .
    working_dir: /app
    depends_on: 
      - redis
      - db
    environment: 
      REDIS_URL: redis://redis:6379/0

      USE_POSTGRES: 'True'
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: postgres

      DEBUG: 'False'
      DISABLE_SSL: 'False'

      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
    command: celery worker --app=telegram_sendall.celery.app --without-heartbeat -l debug


volumes:
  redis_vol:
  redis_insight_vol:
