# Generated by Django 2.2.3 on 2019-07-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='session',
            name='session',
            field=models.TextField(blank=True),
        ),
    ]
