# Generated by Django 2.2.3 on 2019-07-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0002_auto_20190722_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
