# Generated by Django 2.2.3 on 2019-08-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0004_contactslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledDialogsTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.TextField(unique=True)),
                ('ready', models.BooleanField(default=False)),
                ('result', models.TextField()),
            ],
        ),
    ]
