# Generated by Django 2.2.3 on 2019-08-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0005_scheduleddialogstask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledDialogsTask',
        ),
    ]
