# Generated by Django 2.2.3 on 2021-01-21 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendall', '0006_delete_scheduleddialogstask'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('eta', models.DateTimeField(null=True)),
                ('contacts', models.TextField()),
                ('message', models.TextField()),
                ('markdown', models.BooleanField()),
                ('done', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sendall.Session')),
            ],
        ),
    ]
