# Generated by Django 2.2.3 on 2022-11-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0008_auto_20221103_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymessagetask',
            name='markdown',
        ),
        migrations.RemoveField(
            model_name='replymessagetask',
            name='master',
        ),
        migrations.RemoveField(
            model_name='replymessagetask',
            name='message',
        ),
        migrations.AddField(
            model_name='replymessagetask',
            name='dialog_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='replymessagetask',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
