# Generated by Django 2.2.3 on 2022-11-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0009_auto_20221103_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='bot_settings',
            field=models.TextField(default="{'active': False, 'silent': False}"),
        ),
    ]
