# Generated by Django 2.2.3 on 2022-11-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0010_session_bot_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replymessagetask',
            name='done',
        ),
    ]
