# Generated by Django 2.2.3 on 2022-11-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0011_remove_replymessagetask_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlinemessagesettings',
            name='trigger_substring',
            field=models.TextField(default='\\d\\d\\d+'),
        ),
    ]
