# Generated by Django 2.2.3 on 2022-12-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendall', '0012_auto_20221113_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymessagetask',
            name='dialog_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
